### ISSUE TITLE
Missing column error during stats query podcasts allTime

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse-api#578]
```
id too long! https:/www.ruv.is/rss/hladvarp/frjalsar-hendur
row err QueryFailedError: column "undefined" does not exist
    at QueryFailedError.TypeORMError [as constructor] (/tmp/src/error/TypeORMError.ts:7:9)
    at new QueryFailedError (/tmp/src/error/QueryFailedError.ts:9:9)
    at PostgresQueryRunner.<anonymous> (/tmp/src/driver/postgres/PostgresQueryRunner.ts:263:19)
    at step (/tmp/node_modules/typeorm/node_modules/tslib/tslib.js:144:27)
    at Object.throw (/tmp/node_modules/typeorm/node_modules/tslib/tslib.js:125:57)
    at rejected (/tmp/node_modules/typeorm/node_modules/tslib/tslib.js:116:69)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  query: `UPDATE "podcasts" SET "pastAllTimeTotalUniquePageviews"=undefined WHERE id=' - Others';`,
  parameters: undefined,
  driverError: error: column "undefined" does not exist
      at Parser.parseErrorMessage (/tmp/node_modules/pg-protocol/src/parser.ts:369:69)
      at Parser.handlePacket (/tmp/node_modules/pg-protocol/src/parser.ts:188:21)
      at Parser.parse (/tmp/node_modules/pg-protocol/src/parser.ts:103:30)
      at Socket.<anonymous> (/tmp/node_modules/pg-protocol/src/index.ts:7:48)
      at Socket.emit (node:events:513:28)
      at Socket.emit (node:domain:489:12)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
      at Socket.Readable.push (node:internal/streams/readable:228:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 109,
    severity: 'ERROR',
    code: '42703',
    detail: undefined,
    hint: undefined,
    position: '57',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3294',
    routine: 'errorMissingColumn'
  },
  length: 109,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '57',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3294',
  routine: 'errorMissingColumn'
}
row {
  label: '/podcast/ - Others',
  nb_visits: 10,
  nb_hits: 10,
  sum_time_spent: 32,
  nb_hits_with_time_network: 5,
  min_time_network: 0,
  max_time_network: 0.309,
  nb_hits_with_time_server: 5,
  min_time_server: 0.163,
  max_time_server: 0.614,
  nb_hits_with_time_transfer: 5,
  min_time_transfer: 0.022,
  max_time_transfer: 0.413,
  nb_hits_with_time_dom_processing: 5,
  min_time_dom_processing: 0.028,
  max_time_dom_processing: 0.406,
  nb_hits_with_time_dom_completion: 4,
  min_time_dom_completion: 0.531,
  max_time_dom_completion: 1.486,
  nb_hits_with_time_on_load: 4,
  min_time_on_load: 0,
  max_time_on_load: 0.001,
  entry_nb_visits: 6,
  entry_nb_actions: 6,
  entry_sum_visit_length: 0,
  entry_bounce_count: 6,
  exit_nb_visits: 7,
  avg_time_network: 0.189,
  avg_time_server: 0.306,
  avg_time_transfer: 0.185,
  avg_time_dom_processing: 0.239,
  avg_time_dom_completion: 1.045,
  avg_time_on_load: 0.001,
  avg_page_load_time: 1.9649999999999999,
  avg_time_on_page: 3,
  bounce_rate: '100%',
  exit_rate: '70%',
  segment: 'pageUrl=^http%253A%252F%252Fpodverse.fm%252Fpodcast',
  Actions_PageUrl: '/podcast/ - Others',
  is_summary: true
}
id too long! https:/feed.nashownotes.com/rss.xml
```

**Comment by mitchdowney** [comment]
We are archiving all Github issues and PRs that pertain to the previous generation Podverse. The Podverse dev team is currently 100% focused on the next generation app, and will be only working on next gen Github issues going forward.

If you would like to see a work-in-progress demo of the upcoming Podverse website, please visit https://alpha.podverse.fm. Our tentative release date is Spring 2026.

If you're a developer who may be interested in contributing to Podverse Next-Gen, please see our [Local Dev Setup documentation](https://github.com/podverse/podverse-ops/blob/v5-develop/dev/local-dev-setup.md). We can also be reached through [Matrix or Discord](https://podverse.fm/contact).

I'm sorry for the abrupt announcement, but thank you for your bug reports and feature requests.
