### ISSUE TITLE
podverse_api_stats-episodes-allTime job failing

### ISSUE THREAD

**Issue by suorcd** [podverse/podverse-api#588]
job output
```bash
...
> podverse-api@4.10.2 scripts:queryUniquePageviews
> ts-node -r tsconfig-paths/register ./src/scripts/stats/queryUniquePageviews.ts episodes allTime


/tmp/src/services/stats.ts:80
    return data.filter((x) => x.url.length <= limit)
                ^
TypeError: Cannot read properties of undefined (reading 'length')
    at /tmp/src/services/stats.ts:80:37
    at Array.filter (<anonymous>)
    at filterCustomFeedUrls (/tmp/src/services/stats.ts:80:17)
    at /tmp/src/services/stats.ts:91:20
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/src/services/stats.ts:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
...
```

**Comment by mitchdowney** [comment]
We are archiving all Github issues and PRs that pertain to the previous generation Podverse. The Podverse dev team is currently 100% focused on the next generation app, and will be only working on next gen Github issues going forward.

If you would like to see a work-in-progress demo of the upcoming Podverse website, please visit https://alpha.podverse.fm. Our tentative release date is Spring 2026.

If you're a developer who may be interested in contributing to Podverse Next-Gen, please see our [Local Dev Setup documentation](https://github.com/podverse/podverse-ops/blob/v5-develop/dev/local-dev-setup.md). We can also be reached through [Matrix or Discord](https://podverse.fm/contact).

I'm sorry for the abrupt announcement, but thank you for your bug reports and feature requests.
