### ISSUE TITLE
Parser Error: Fetching error

### ISSUE THREAD

**Issue by KyleFDowney** [podverse/podverse-api#96]
> parseFeedUrl,start,12945ms,feedUrl.url http://intechwetrustpodcast.com/feed/,
parseFeedUrl error: Error: Fetching error.
    at Object.<anonymous> (/mnt/c/Users/podve/repos/podverse-api/node_modules/@podverse/podcast-feed-parser/index.js:7:21)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/mnt/c/Users/podve/repos/podverse-api/src/services/parser.ts:10:27)
    at Module._compile (internal/modules/cjs/loader.js:776:30)

**Comment by mitchdowney** [comment]
This feedUrl is currently a dead link. I think I'm just going to ignore these types of failures, since our integration with the Podcast Index should prevent us from excessively re-parsing dead feeds.
